spring:
  application:
    name: bookrate-service-order
  zipkin:
    base-url: http://localhost:8061
    
server:
  port: 8052

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8050/eureka/

