spring:
  application:
    name: bookrate-service-book
  zipkin:
    base-url: http://localhost:8061
    
server:
  port: 8051

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8050/eureka/
