spring:
  application:
    name: bookrate-service-user
  zipkin:
    base-url: http://localhost:8061
    
server:
  port: 8053
  
feign:
  hystrix:
    enabled: true

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8050/eureka/

